export { default as AddTestimonialModal } from './addTestimonialModal';
export { default as EditTestimonialModal } from './editTestimonialModal';
export { default as VideoRatingModal } from './ratingModal';
export { default as TipModal } from './tipModal';
export { default as ShareModal } from './shareModal';
export { default as FilterModal } from './filterModal';
export { default as PaymentModal } from './paymentModal';
export { default as TopUpModal} from './topUpModal';
export { default as WithDrawModal } from './withDraw';
export { default as StripeCheckoutModal } from './StripeCheckoutModal';
